"""
Ronny getz
Client constants: port, IP, protocol indices, param counts.
"""
PORT = 1800
IP = "127.0.0.1"
MSG_LEN = 10
PARAMETERS = 1
REQUEST = 0
HAVE_PARAMETERS = 1
FOLDER = 0
FILE = 0
COPY_TO_FOLDER = 1
SOFTWARE = 0
CHUNK = 1024
FILE_SEND_FILE = 1
NAME_INDEX = -1
EOF = b"-1"
NO_PARAMETERS = 0
PARAMETER = 1
TWO_PARAMETERS = 2
USERNAME = 1
PASSWORD = 2
LOGIN_PARAMS = 4
SIGNUP_PARAMS = 5
GET_NOTEBOOK_PARAMS = 3
ADD_NOTEBOOK_PARAMS = 4
ADD_NOTEBOOK_DB_PARAMS = 6
CLIENTS_NOTEBOOKS_PARAMS = 3
